Eventyrere
----------

* Barbar
  Slår 2d10 i angrep sammen med 1d8 i forsvar.

  +lvl: +1d10 i angrep

  ◊ Kamprop: Eventyrerne får initiativet og barbaren får +1 resten av kampen.
   Whirlwind: Slå én terning mot hver motstander i rommet.

* Skytter
  +1 i skyting

  +lvl: +1 i angrep i skyting
  +lvl: +1 terning i skyting

   Ekstra skudd øyeblikkelig etter det vanlige
  ◊ Trickshot - ufarliggjør en felle på avstand (botch på 1-er)

* Tjuv
  +1 terning mot feller
  +2 i angrep i nærkamp
  +2 i forsvar mot skyting

  +lvl: +1 terning mot feller

   Scout ahead: Se på ett fellerom fremover per level.
  ◊ Backstab: Nærkampangrep før skyting. Skjelettet får ikke bruke noe av sitt utstyr. Sønderknuser.

* Kriger
  +1 i nærkamp
  +1 terning i nærkamp
  Kan bruke sverdterninger etter terningsslaget

  +lvl: +1 terning i nærkamp

   Sønderknus et skjelett han har overvunnet
   Dra ut igjen pila av skulderen: +3 i forsvar mot skyting

* Soldat
  +3 i forsvar

  +lvl: +1 terning i kamp

   Shield bash (på uavgjort): Skjelettet kan bare forsvare seg i neste nærkamprunde.
   Disarm: Skjelettet sloss uten våpen resten av kampen.

* Prest
  Velsigner alle med omslag i kamp og mot seid.
  Hver kan slå om igjen én 1-er én gang per kamp.

  +lvl: slå om igjen en ekstra gang per kamp
  +lvl: slå om igjen høyere slag (lvl 2 = 2-ere)

  ◊ Heal: gi annen eventyrer +2 i forsvar (etter terningsslag)
  ◊ Ressurect: gjenoppliv en død eventyrer (etter kamp/felle)

* Munk
  Kan forvise ett skjelett på starten av kampen. Det blir immunt.
  +1 i kamp

  +lvl: +1 terning i kamp

  ◊ Blendende lys: Skjelettet kan ikke bruke sitt utstyr neste runde.
  ◊ Maktord: Sønderknus et tidligere forvist skjelett.

* Magiker
  3 mana

  +lvl: +2 mana
  +lvl: +1 terning mot seid

  1 mana: snu en kamptriksterning til vilkårlig side
  1 mana: endre hvilken eventyrer som dør
  1 mana: flammende fingre: +4 i angrep i nærkamp resten av kampen
  2 mana: utsett et seid (en kamprunde til først)
  2 mana: skyt missiler mot en fiende: 3d10
  3 mana: ildkule: 3 fiender dør på [1][2][3]

  ◊ Usynlighet: Ta magikeren helt ut av kampen.
  ◊◊ Manaflod: Alle egenskaper koster 1 mana mindre.
