* MIX - Magnars Infernalske Kryptspill

  MIX er et brettspill for to personer. Du er en nekromanser som
  påkaller skjeletter til å gjennomføre dine onde planer. De slåss og
  samler ressurser i skogen, fanger folk i landsbyen og bygger din
  mørke krypt full av feller. I løpet av spillets gang kommer
  eventyrere for å stoppe deg, og til slutt en skare ilske bønder med
  fakler og høygafler som har fått nok av din plagsomme
  tilstedeværelse.

* Grove trekk

  Spillet foregår over 23 runder, også kjent som dager. Hver morgen
  bestemmer du hva skjelettene dine skal ta seg til den dagen. De kan:

  1. Dra til skogen og samle ressurser.
  2. Dra til landsbyen og fange folk.
  3. Bygge i krypten.

  *Ressurser* brukes for å kjøpe verktøy og feller. *Folk* ofres i
  skrekkelige seremonier, som oftest for å påkalle flere
  skjeletter. *Bygging i krypten* er essensielt for å overleve
  angrepene som vil komme.

* En rask innføring i spillets gang
** Starten

   Hver spiller starter med syv ressurser, noen grunnleggende
   felleidéer, en inngang til krypten og tre lydige skjeletter. Et av
   skjelettene starter med et tilfeldig våpen.

** Dag 1 til 11

   Du samler ressurser for å kjøpe verktøy og feller, og prøver å få
   bygd en krypt som kan motstå det første angrepet. Samtidig må du
   bygge et fangehull, slik at du kan starte å samle folk for å
   påkalle flere skjeletter.

** Tre eventyrere angriper

   På kvelden den 11. dagen angriper tre eventyrere. Da må du ha
   bygget et *oppholdsrom* til deg selv i krypten, slik at du har et
   sted å gjemme deg når de angriper.

   Din motspiller styrer eventyrerne. De trenger seg inn i krypten,
   slipper løs fanger, roter i papirer og angriper skjelettene dine.
   Skulle de nå helt inn i ditt kammers og ta rotta på deg, har du
   heldigvis noen triks opp ermet. Men det er langt i fra noen
   ønskelig situasjon.

   Når angrepet er over kan du gå over de døde eventyrerne og lete
   etter plynder.

** Dag 12 til 17

   Skjelettene slikker sårene etter angrepet, men det er bare seks
   dager til det neste. Det må bygges nye, bedre feller, skjelettene
   må skaffe bedre verktøy, og du burde kanskje ha noen flere
   skjeletter også. Det er generelt sett alt for dårlig tid.

** Fem eventyrere angriper

   På kvelden den 17. dagen angriper fem enda kvassere eventyrere. For
   å overleve det må du enten ha bygget et nytt oppholdsrom bak enda
   flere feller, ha studert fram noen skrekkelige seid, eller ha trent
   opp og skaffet bra våpen til skjelettene dine.

** Dag 18 til 23

   Nå kommer bøndene snart. Dere må klargjøre krypten for et massivt
   angrep. Du kjøper flusst med feller for å finne de som tar livet av
   flest mulig inntrengere. Rekker du å få opp alle fellene, og med et
   bra oppholdsrom innerst?

** Bøndene svermer inn i krypten

   På kvelden den 23. og siste dagen kommer bøndene. De svermer inn i
   bølge etter bølge og overvelder skjelettene med sin store skare.
   Fella som drepte to av eventyrerne virker ikke være like effektiv
   lengre.

   Ingen av nekromanserne overlever angrepet.

   Vinneren er den som klarte å drepe flest bønder før han måtte bøte
   med livet.

* Sette opp spillet

  Før spillet starter er det greit å ha orden på bordet:

** Sett opp sentralt spilleområde:

  - Plasser terninger, steiner og ressurser i lett rekkevidde for begge spillere.
  - Stokk sammen alle Akt 1 skogshendelser og ha lett tilgjengelig.
  - Legg alle våpenbrikker (spyd, sverd, øks og bue) i en skål.
  - Legg alle verktøybrikker (hakke, spade, klubbe) i en annen skål.
  - Legg resten av brikkene i en tredje skål.
  - Legg ut den tomme markedsplassen.
  - Gi en av spillerne den store dagsterningen (20-sider).
  - Resten av kortene kan plasseres perifert og finnes fram ved behov.

** Del ut til begge spillere:
  - 2 tilfeldige nekromansere (velg én av dem)
  - 2 tilfeldige innganger (velg én av dem)
  - 3 skjeletter
  - 1 sett med startrom (markert med stjerne)
  - 1 tilfeldig våpen (gi til ett av skjelettene)
  - 7 ressurser (legg på nekromanser-kortet)

Når nekromansere og innganger er valgt kan resten av disse kortene
legges tilbake i esken - de er ikke i bruk denne gangen.

* Hva er alle disse tingene jeg har fått?

  - *Nekromanseren* er din avatar i spillet. Alle nekromansere har
    unike egenskaper.

  - *Inngangen* er starten på krypten der du holder til, og er det
    første rommet inntrengere ankommer.

  - *Skjelettene* gjør alt arbeidet, samler ressurser, mennesker og
    bygger på krypten.

  - *Romkort* blir en del av krypten når skjelettene har bygget dem
    ferdig.

  - *Verktøy* som hakke, spade og klubbe gjør arbeidet lettere for
    skjelettene.

  - *Våpen, rustning og andre brikker* hjelper skjelettene i kamp.

  - *Ressurser* brukes til å kjøpe romkort og verktøy.

* Ett døgn

  Spillet består av 23 runder, eller døgn. På noen av disse dagene blir
  krypten angrepet, ellers er de likt oppbygget.

** Planlegging

   Dette er delen av runden hvor du tar de store avgjørelsene. Det
   viktigste du gjør er å bestemme hva alle skjelettene skal gjøre
   denne dagen.

   - Legg en *byggestein* foran skjelettet for å sende det inn i
     krypten for å bygge.

   - Legg en *ressurs* foran skjelettet for å sende det ut i skogen
     for å samle ressurser.

   - Legg en *fangestein* foran skjelettet for å sende det til
     landsbyen for å fange folk til ditt fangehull.

   Du bruker også planleggingsfasen til andre ting:

   - Kjøpe verktøy (hakke, spade, klubbe) for 3 ressurser.

   - Kjøpe romkort for 3 ressurser.

   - Planlegge bygging i krypten.

   - Ofre fem fanger for å påkalle et nytt skjelett (krever bistand
     fra 2 skjeletter).

   - Legge en studiestein på et studie eller bibliotek.

   - Avholde en seremoni med et seidekort.

** Ute på arbeid

   Alle skjelettene som er ute på arbeid slår 1d6. Slå alle terningene
   på likt, blå for bygging, grønne for ressurser, hvite for fanger.

   - Skjeletter med *hakke* kan slå om igjen én 1-er på byggeterning.

   - Skjeletter med *spade* kan slå om igjen én 1-er på ressursterning.

   - Skjeletter med *klubbe* kan slå om igjen én 1-er på fangeterning.

  Deretter halverer og runder de ned tallet på terningen. Altså får
  man for eksempel i skogen:

  - 1 på terningen: 0 ressurser
  - 2 på terningen: 1 ressurs
  - 3 på terningen: 1 ressurser
  - 4 på terningen: 2 ressurser
  - 5 på terningen: 2 ressurser
  - 6 på terningen: 3 ressurser

  La ressursene ligge på skjelettene, for nå skjer det saker i skogen.

** Hendelser i skogen

   Hvis du har vært i skogen trekker din motspiller et kort fra
   hendelsesbunken og leser høyt. Noen ganger må du gjøre valg før
   motspilleren leser videre.

   Gjennomfør kortet, og legg det så bort. Kortet er brukt.

   Det skjer én hendelse for hver spiller som har hatt skjeletter i
   skogen.

** Ferdig med studier

   Hvis du nå har nok studiesteiner på et studie eller bibliotek, så
   fjern dem og trekk seid tilsvarende det som står på kortet.

** Angrep?

   Hvis det er dag 11, 17 eller 23 avsluttes nå runden med et angrep
   på krypten. Se "Angrepene" lengre nede i reglene.

* Dine første feller
** Vaktpost
** Snubletråd
** Fangehull

** Snekkerbod

** Arbeidsbenk

** Kaffestasjon

** 2x Soverom

* Kampsystemet

  En kamp består av:

  - én runde med skyting
  - deretter nærkamprunder til en side har vunnet

  Før og mellom alle disse rundene kan nekromanseren bruke ett kampseid, og
  eventyrere kan bruke sine spesialegenskaper.

** Skyting

   Alle skyter på likt, så to skyttere kan drepe hverandre.

   Dersom noen kan skyte flere ganger, så får de muligheten når alle har skutt
   første runde - hvis de fortsatt lever.

** Nærkamp

* Angrepene

  På kvelden dag 11, så 17 og til slutt 23 blir krypten angrepet.

  Inntrengernes mål er å finne deg, nekromanseren. Du er nødt til å
  være i et ferdig bygget *Oppholdsrom*. Hvis du har flere oppholdsrom
  i krypten, skriv ned din posisjon på en hemmelig lapp.

  Dersom du ikke har noen oppholdsrom, så møter du inntrengerne i
  inngangen med et av dine skjeletter som livvakt.

  For å finne deg må inntrengerne begi seg gjennom krypten, komme seg
  forbi feller og slåss mot skjelettene som står på vakt.

*** Forskjellige typer feller

    De aller fleste feller fungerer bare én gang per angrep. Og det er
    for det meste greit mot eventyrerne. Men bøndene kommer i bølge
    etter bølge. Da er det kjekt med feller som er *Alltid aktive*.
    Hver gang inntrengere går inn i et slikt rom, utløses fella på
    nytt.

    Skjeletter står på vakt i en god del rom. Du velger selv hvilke og
    hvor mange skjeletter som er tilstede i det inntrengerne ankommer
    rommet. Velg blant skjelettene som er uthvilte. Hvis du ikke har
    noen uthvilte skjeletter, kan du velge blant de som er utslått.
    Men taper de igjen, så blir de sønderknust - og kan ikke velges
    på nytt.

    Noen rom utløses i det inntrengerne kommer inn i naborommet. Flipp
    rommet opp når inntrengerne kommer inn i rommet ved siden av. Du kan
    selv velge hvilket av de to kortene som får effekt først.

    Andre rom er *Blindganger*. Du kan ikke bygge rom bakenfor en
    blindgang.

    Det er også viktig å ha et *Oppholdsrom*. Det er i disse du kan
    oppholde deg under angrepet. Mer om det i neste avsnitt.

    Noen få oppholdsrom er også *Templer*. Du kan bare bygge ett
    tempel i din krypt. Tempelet lar deg ofre fanger (et såkalt
    Tempeloffer) for å gjøre Kampseid enda bedre, dersom du bruker det
    som oppholdsrom.

*** Oppgjør i oppholdsrommet

    Dersom de finner deg, så har du i oppholdsrommet ditt med deg ett av
    skjelettene dine som livvakt. Det er nå du kan bruke Kampseid hvis du
    har det. Så lenge livvakten er i live, kan du ikke dø.

    Skulle inntrengerne klare å ta livet av deg, så sier de seg fornøyd
    og forlater krypten. Du har et siste triks i ermet. Ved å trekke
    livskraften ut av to av dine skjeletter kommer du deg til hektene
    igjen. De to skjelettene sønderknuses i prosessen.

** De tre forskjellige angrepene
*** Dag 11: Tre eventyrere

    Trekk tre tilfeldige eventyrere og slå 5 kamptriksterninger for
    dem. De er i utgangspunktet level 1, men kan få ekstra levels fra
    kamptriksterningene.

*** Dag 17: Fem eventyrere

    Trekk fem tilfeldige eventyrere og slå 7 kamptriksterninger for
    dem. De er i utgangspunktet level 2, men kan få ekstra levels fra
    kamptriksterningene.

*** Dag 23: Bøndene angriper

    Bøndene kommer i bølge etter bølge helt til du er død. Vinneren
    er den som overlever lengst, altså dreper flest bønder.

    Når første bølge er utradert, kommer neste bølge:

    - Først 20 bønder som slåss med d8. Svermen starter på 6 bønder.
    - Så 20 bønder som slåss med d8+1.
    - Så 20 bønder som slåss med d10.
    - Så 20 bønder som slåss med d10. Svermen starter på 8 bønder.
    - Så 20 bønder som slåss med d10. Svermen starter på 10 bønder.

    Skulle du mot formoding ha overlevet alt dette, så fortsetter svermen
    å øke med to av gangen.

    Bøndene har en ekstra egenskap når de svermer. De som slår 1 på
    terningen flykter midlertidig. Ta de ut av terningsslaget før du
    beregner dødsfall.
* Endringsliste
** Søndag 6. januar 2013
*** Hendelsesbunken
    - Ikke stokk hendelsesbunken. Bare trekk fra toppen, og legg vekk underveis.
    - Stokk inn akt 2-hendelser etter angrepet dag 11.
    - Stokk inn akt 3-hendelser etter angrepet dag 17.
*** Uendelige løkker
    - Visse kombinasjoner av Alltid Aktiv og andre kort kan skape
      uendelige løkker. I en slik situasjon, så mister kortet sin
      Alltid Aktiv-status etter første reaktivering. Det vil si at du
      får én reaktivering, men så er festen over.
