* MIX - Magnars Infernalske Kryptspill

  MIX er et brettspill for to personer. Du er en nekromanser som
  påkaller skjeletter til å gjennomføre dine onde planer. De slåss og
  samler ressurser i skogen, fanger folk i landsbyen og bygger din
  mørke krypt full av feller. I løpet av spillets gang kommer
  eventyrere for å stoppe deg, og til slutt en skare ilske bønder med
  fakler og høygafler som har fått nok av din plagsomme
  tilstedeværelse.

* Grove trekk

  Spillet foregår over 23 runder, også kjent som netter. Hver kveld bestemmer du
  hva skjelettene dine skal ta seg til den natten. De kan:

  1. Dra til skogen og samle ressurser.
  2. Dra til landsbyen og fange folk.
  3. Bygge i krypten.

  *Ressurser* brukes for å kjøpe utstyr og feller. *Folk* ofres i skrekkelige
  seremonier, som oftest for å påkalle flere skjeletter. *Bygging i krypten* er
  essensielt for å overleve angrepene som vil komme.

* En rask innføring i spillets gang
** Starten

   Hver spiller starter med syv ressurser, noen grunnleggende felleidéer, en
   inngang til krypten og tre lydige skjeletter. Et av skjelettene starter med et
   tilfeldig våpen.

** Natt 1 til 11

   Du samler ressurser for å kjøpe utstyr og feller, og prøver å få bygd en krypt
   som kan motstå det første angrepet. Samtidig må du bygge et fangehull, slik at
   du kan starte å samle folk for å påkalle flere skjeletter.

** Tre eventyrere angriper

   Dagen etter den 11. natten angriper tre eventyrere. Da må du ha bygget et
   *oppholdsrom* til deg selv i krypten, slik at du har et sted å gjemme deg når de
   angriper.

   Din motspiller styrer eventyrerne. De trenger seg inn i krypten, slipper løs
   fanger, roter i papirer og angriper skjelettene dine. Skulle de nå helt inn i
   ditt kammers og ta rotta på deg, har du heldigvis noen triks opp ermet. Men det
   er langt i fra noen ønskelig situasjon.

   Når angrepet er over kan du gå over de døde eventyrerne og lete etter plynder.

** Natt 12 til 17

   Skjelettene slikker sårene etter angrepet, men det er bare seks netter til det
   neste. Det må bygges nye, bedre feller, skjelettene må skaffe bedre utstyr, og du
   burde kanskje ha noen flere skjeletter også. Det er generelt sett alt for dårlig
   tid.

** Fem eventyrere angriper

   Dagen etter den 17. natten angriper fem enda kvassere eventyrere. For å overleve
   det må du enten ha bygget et nytt oppholdsrom bak enda flere feller, ha studert
   fram noen skrekkelige seid, eller ha trent opp og skaffet bra utstyr til
   skjelettene dine.

** Natt 18 til 23

   Nå kommer bøndene snart. Dere må klargjøre krypten for et massivt angrep. Du
   kjøper flusst med feller for å finne de som tar livet av flest mulig
   inntrengere. Rekker du å få opp alle fellene, og med et bra oppholdsrom innerst?

** Bøndene svermer inn i krypten

   Dagen etter den 23. og siste natten kommer bøndene. De svermer inn
   i bølge etter bølge og overvelder skjelettene med sin store skare.
   Fella som drepte to av eventyrerne virker ikke være like effektiv
   lengre.

   Ingen av nekromanserne overlever natten.

   Vinneren er den som klarte å drepe flest bønder før han måtte bøte
   med livet.

* Sette opp spillet

  Før spillet starter er det greit å ha orden på bordet:

** Sett opp sentralt spilleområde:

  - Plasser terninger, steiner og ressurser i lett rekkevidde for begge spillere.
  - Stokk sammen alle Akt 1 skogshendelser og ha lett tilgjengelig.
  - Legg alle våpenbrikker (spyd, sverd, øks og bue) i en skål.
  - Legg alle utstyrsbrikker (hakke, spade, klubbe) i en annen skål.
  - Legg resten av brikkene i en tredje skål.
  - Legg ut den tomme markedsplassen.
  - Gi en av spillerne den store dagsterningen (20-sider).
  - Resten av kortene kan plasseres perifert og finnes fram ved behov.

** Del ut til begge spillere:
  - 2 tilfeldige nekromansere (velg én av dem)
  - 2 tilfeldige innganger (velg én av dem)
  - 3 skjeletter
  - 1 sett med startrom (markert med stjerne)
  - 1 tilfeldig våpen (gi til ett av skjelettene)
  - 7 ressurser

Når nekromansere og innganger er valgt kan resten av disse kortene
legges tilbake i esken - de er ikke i bruk denne gangen.

* Hva er alle disse tingene jeg har fått?

  - *Nekromanseren* er din avatar i spillet. Alle nekromansere har
    unike egenskaper.

  - *Inngangen* er starten på krypten der du holder til, og er det
    første rommet inntrengere ankommer.

  - *Skjelettene* gjør alt arbeidet, samler ressurser, mennesker og
    bygger på krypten.

  - *Romkort* blir en del av krypten når skjelettene har bygget dem
    ferdig.

  - *Utstyr* som hakke, spade og klubbe gjør arbeidet lettere for
    skjelettene.

  - *Våpen, rustning og andre brikker* hjelper skjelettene i kamp.

  - *Ressurser* brukes til å kjøpe romkort og utstyr.

* Ett døgn
** Planlegging
** Ute på arbeid
** Hendelser i skogen

** Ferdig med studier

** Angrep?

* Dine første feller
** Vaktpost
** Snubletråd
** Fangehull

** Snekkerbod

** Arbeidsbenk

** Kaffestasjon

** 2x Soverom

* Kampsystemet

  En kamp består av:

  - én runde med skyting
  - deretter nærkamprunder til en side har vunnet

  Før og mellom alle disse rundene kan nekromanseren bruke ett kampseid, og
  eventyrere kan bruke sine spesialegenskaper.

** Skyting

   Alle skyter på likt, så to skyttere kan drepe hverandre.

   Dersom noen kan skyte flere ganger, så får de muligheten når alle har skutt
   første runde - hvis de fortsatt lever.
