* MIX - Magnars Infernalske Kryptspill

  MIX er et brettspill. Du er en nekromanser som påkaller skjeletter til å
  gjennomføre dine onde planer. De slåss og samler ressurser i skogen, fanger folk
  i landsbyen og bygger din mørke krypt full av feller. I løpet av spillets gang
  kommer eventyrere for å stoppe deg, og til slutt en skare ilske bønder med
  fakler og høygafler som har fått nok av din plagsomme tilstedeværelse.

* Grove trekk

  Spillet foregår over 23 runder, også kjent som netter. Hver kveld bestemmer du
  hva skjelettene dine skal ta seg til den natten. De kan:

  1. Dra til skogen og samle ressurser.
  2. Dra til landsbyen og fange folk.
  3. Bygge i krypten.

  **Ressurser** brukes for å kjøpe utstyr og feller. **Folk** ofres i skrekkelige
  seremonier, som oftest for å påkalle flere skjeletter. **Bygging i krypten** er
  essensielt for å overleve angrepene som vil komme.

* Spillets gang

** Starten

   Hver spiller starter med syv ressurser, noen grunnleggende felleidéer, en
   inngang til krypten og tre lydige skjeletter. Et av skjelettene starter med et
   tilfeldig våpen.

** Natt 1 til 11

   Du samler ressurser for å kjøpe utstyr og feller, og prøver å få bygd en krypt
   som kan motstå det første angrepet. Samtidig må du bygge et fangehull, slik at
   du kan starte å samle folk for å påkalle flere skjeletter.

** Tre eventyrere angriper

   Dagen etter den 11. natten angriper tre eventyrere. Da må du ha bygget et
   *oppholdsrom* til deg selv i krypten, slik at du har et sted å gjemme deg når de
   angriper.

   Din motspiller styrer eventyrerne. De trenger seg inn i krypten, slipper løs
   fanger, roter i papirer og angriper skjelettene dine. Skulle de nå helt inn i
   ditt kammers og ta rotta på deg, har du heldigvis noen triks opp ermet. Men det
   er langt i fra noen ønskelig situasjon.

   Når angrepet er over kan du gå over de døde eventyrerne og lete etter plynder.

** Natt 12 til 17

   Skjelettene slikker sårene etter angrepet, men det er bare seks netter til det
   neste. Det må bygges nye, bedre feller, skjelettene må skaffe bedre utstyr, og du
   burde kanskje ha noen flere skjeletter også. Det er generelt sett alt for dårlig
   tid.

** Fem eventyrere angriper

   Dagen etter den 17. natten angriper fem enda kvassere eventyrere. For å overleve
   det må du enten ha bygget et nytt oppholdsrom bak enda flere feller, ha studert
   fram noen skrekkelige seid, eller ha trent opp og skaffet bra utstyr til
   skjelettene dine. Denne gangen kommer det også en navngitt eventyrer som leder
   gjengen, med helt spesielle egenskaper.

** Natt 18 til 23

   Nå kommer bøndene snart. Dere må klargjøre krypten for et massivt angrep. Du
   kjøper flusst med feller for å finne de som tar livet av flest mulig
   inntrengere. Rekker du å få opp alle fellene, og med et bra oppholdsrom innerst?

** Bøndene svermer inn i krypten

   Dagen etter den 23. og siste natten kommer det minst 30 bønder og angriper. De
   svermer inn og overvelder skjelettene med sin store skare. Fella som drepte to
   av eventyrerne virker ikke være like effektiv lengre. Kan du motstå floden?

   Spillerne som overlever har vunnet.

   Men her er det en tvist. Før angrepet velger hver spiller i all hemmelighet hvor
   mange bønder hen tror hen kan klare. Ikke færre enn 30. Så mange bønder
   angriper. Dersom flere spillere overlevet angrepet, så vinner den aller mest som
   tok flest bønder.

* Ett døgn

** Dagens omstendigheter

** Planlegging

** Ute på arbeid

** Hendelser i skogen

** Ferdig med studier

** Angrep?

* Dine første feller

** Vaktpost

** Snubletråd

** Fangehull

** Snekkerbod

** Arbeidsbenk

** Kaffestasjon

** 2x Soverom

* Kampsystemet

  En kamp består av:

  - én runde med skyting
  - deretter nærkamprunder til en side har vunnet

  Før og mellom alle disse rundene kan nekromanseren bruke ett kampseid, og
  eventyrere kan bruke sine spesialegenskaper.

** Skyting

   Alle skyter på likt, så to skyttere kan drepe hverandre.

   Dersom noen kan skyte flere ganger, så får de muligheten når alle har skutt
   første runde - hvis de fortsatt lever.
